services:
  mongodb:
    image: mongo
    container_name: xphish_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: xphish-vision-demo
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo_data:
